<?php 
	$imageUrl = '';
	if($this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getFooterLogo()){
		$imageUrl = $this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->getFooterLogo();
	}
	$helper = $this->helper('Rokanthemes\RokanBase\Helper\Data');
	$enableMenu = $helper ->getConfigData('themeoption/footer/footer_menu_mobile');
?>
<div id="focus-area"></div>
<div id="back-top" class=""><i class="icon icon-chevrons-up"></i></div>
<div class="footer-container <?php if($enableMenu){ ?>enable-mobile-menu<?php } ?> footer-sport" >
	<div class="footer-top">
		<div class="footer content">
			<div class="container-inner">
				<div class="footer-static_link flex-layout space-between">
					<div class="footer-links">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_footer_customer_service_sport')->toHtml(); ?>
					</div>
					<div class="footer-links">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_footer_myaccount_sport')->toHtml(); ?>
					</div>
					<div class="footer-links footer-looking">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bluesky_dukamarket_store_01_about_store')->toHtml(); ?>
					</div>
					<div class="footer-links footer-about-store">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_footer_company_introduction')->toHtml(); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="footer content">
			<div class="container-inner border-top flex-layout space-between center_vertical justify-center">
				<?php echo $this->getChildHtml("copyright"); ?>	
				<div class="footer-payment">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bluesky_dukamaket_sport_01-footer-payment')->toHtml(); ?>
				</div>
			</div>
		</div>	
	</div> 
</div>
<?php if($enableMenu){ ?>
<div class="fixed-bottom d-block d-md-none">
	<div class="link-on-bottom">
		<ul class="mobile-bottom-link flex-layout space-between list-unstyled no-wrap">
			<li><a href="<?php echo $this->getUrl('');?>"><span class="icon icon-home1"></span><?= $block->escapeHtml(__('Home')) ?></a></li>
			<li><a href="<?php echo $this->getUrl('customer/account/');?>"><span class="icon icon-user"></span><?= $block->escapeHtml(__('Account')) ?></a></li>
			<li><a href="#" class="toggle-nav-footer"><span class="icon icon-menu"></span><?= $block->escapeHtml(__('Menu')) ?></a></li>
			<li><a href="<?php echo $this->getUrl('wishlist');?>"><span class="icon icon-wishlist"></span><?= $block->escapeHtml(__('Wishlist')) ?></a></li>
			<li><a href="<?php echo $this->getUrl('checkout/cart/');?>"><span class="icon icon-cart"></span><?= $block->escapeHtml(__('Cart')) ?></a></li>
			
		</ul>
	</div>
</div>
<?php } ?>